### ISSUE TITLE
Website Dead Links (From AB3)

### ISSUE THREAD

**Issue by starchypotatocode** [AY2425S1-CS2103T-W14-3/tp#114]
Copied from Forum (appears to be Tutorials tab - do we keep or delete?):

Within [AB3 Developer Guide -> Setting up and getting started -> Before you write code](https://nus-cs2103-ay2425s1.github.io/tp/SettingUp.html#before-writing-code), there is section 4. Do the tutorials, and the links for Tracing code, Adding a new command, and Removing fields all lead to a Page not found error.

**Comment by yuvrajaryan** [comment]
These are deadlinks on the ab3 website as well. can resolve? 

https://se-education.org/addressbook-level3/SettingUp.html
