### ISSUE TITLE
Inclusiveness when Using Names

### ISSUE THREAD

**Issue by taggyhan** [AY2425S1-CS2103T-W14-3/tp#125]
Names should only contain alphanumeric characters and spaces, and it should not be blank
Should names be allowed to have digits? I,e elon musk has a kid named X Æ A-12 Musk" - not sure how inclusive we need to be in this mod - and hall has high percentage of international students which may have this "unusual names "

**Comment by starchypotatocode** [comment]
To clarify: Do you mean the digits thing? Can note in UG that only ASCII allowed due to technical limitations ig
