### ISSUE TITLE
limit to no of sesisons displayed for each member

### ISSUE THREAD

**Issue by taggyhan** [AY2425S1-CS2103T-W14-3/tp#128]
towards end of sem, many members will have multiple sessions - considering hall does like x 4 cca per week , meaning the no of attended session displayed would be quite a lot - should we put a limit on how much is displayed on the UI?

**Comment by starchypotatocode** [comment]
Add a screenshot showing how this is an issue if you can,
IMO this is a Won't Fix because adding that hard limit means there needs to be a way of getting around it for the purposes of the user knowing which sessions a member has attended (and thus to delete if appropriate)?
