### ISSUE TITLE
[PE-D][Tester D] Not possible to update session details after session is created

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-W14-3/tp#185]
This issue is similar to #2, where the session members are confirmed and cannot be changed once the session is created. As such, this could be problematic when there are members who did not get their attendance tracked when the session is created, but say afterwards (could be due to sick or MC)

Adding the session again for the user creates a new, duplicate session that is different from the original session, and this has been mentioned in #2.

Aside from this, the session name and date can also not be changed, which can be very annoying for users who made a mistake while typing the command (and even more so when the command gets very long with many members). This means that the session needs to be deleted and re-created for all of the members (again, this is very problematic if there are a lot of members who was in the session, the poor user has to remember all the members who participated)

This goes the same for the number of points for the session, if later the points get revisited, it will cause quite the headache for the user to fix.

A suggestion for this is to have an update_session command, similar to the update_member command which allows editing of details for a session and all the members in that session.

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: sayomaki/ped#4

**Comment by keithxun** [comment]
duplicate issue, add to dg
