### ISSUE TITLE
[PE-D][Tester D] Command names are slightly too long for users to type out (>10 characters)

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-W14-3/tp#187]
From an user's perspective, having the command names being so long (greater than 10 characters) is quite inconvenient as they will need to type the full command every single time. There is also the _ (underscore) character in some commands (i.e. `add_session`, `add_member`) which needs two keypresses on a standard computer keyboard.

This could be a slight inconvenience, but for the more active users of your application, this can accumulate and become quite significant in terms of time taken to enter commands.

A suggestion for this is to either have command aliases, or split up the command name to have sub-commands separated by a space, which is easier to type (and press!) compared to having an underscore.

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: sayomaki/ped#5

**Comment by keithxun** [comment]
Add into dg to have alternative such as addm as future enhancement
