### ISSUE TITLE
[PE-D][Tester C] Error display message could be more specific

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-W14-3/tp#194]
If I were to do `add_member n/John Doe r/4-!!!!!-301 t/johndoe123 tag/logistics`, the result message includes the following statement: `Unfortunately, non-numeric block or room numbers are currently unsupported.`. I believe that this sentence in the result message should state that it applies to floor numbers as well as I believe allowing only integers for either your `BLOCK`, `FLOOR` or `ROOM_NUMBER` is the intended behaviour you want as well.

![Screenshot 2024-11-08 at 5.10.24 PM.png](https://raw.githubusercontent.com/nws321/ped/main/files/1819832c-3314-4125-95d3-c011384cbe28.png)

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: nws321/ped#10

**Comment by keithxun** [comment]
Minor fix to error message

**Comment by starchypotatocode** [comment]
Are we allowed to fix?? Short of making things less specific

**Comment by keithxun** [comment]
Error message should be ok
